name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.3'
          dune-cache: true
          allow-prerelease-opam: true

      - name: Deps
        run: opam install odig twirp_core twirp_cohttp_lwt_unix twirp_ezcurl twirp_tiny_httpd

      - name: Build
        run: opam exec -- odig odoc --cache-dir=_doc/ twirp_core twirp_cohttp_lwt_unix twirp_ezcurl twirp_tiny_httpd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_doc/html
          destination_dir: .
          enable_jekyll: false
