name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    name: build
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        os:
            - ubuntu-latest
              #- macos-latest
              #- windows-latest
        ocaml-compiler:
            - '4.12.1'
            - '4.14'
            - '5.03'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam install mccs
      - run: opam install . -t --deps-only
      - run: opam exec -- dune build @install --ignore-promoted-rules
      - run: opam exec -- dune runtest --ignore-promoted-rules

